### PR TITLE
repl.py run_command() returns response when appropriate

### PR DESCRIPTION
**Pull request by ahundt**

### CODE REVIEW

**Comment by thehunmonkgroup** [comment]
Can you please provide a written description of what you're trying to accomplish with this PR? The extra context will be helpful for the code review.

**Comment by ahundt** [comment]
I have an independent repository that contains a slightly modified [chatgpt-wrapper](https://github.com/mmabrouk/chatgpt-wrapper/tree/main)/[chatgpt_wrapper](https://github.com/mmabrouk/chatgpt-wrapper/tree/main/chatgpt_wrapper)/main.py that's calling these functions, and in that version I use the return values.

My goal was to make minimal changes to integrate a modified version of your main `chatgpt` with a separate pre-existing command line interface I have whose parser ags that don't conflict, while still retaining the existing functionality of your `chatgpt` app, which I've done over there. My existing code base is one where creating custom plugins or a full new app is simply overkill, so I add a call to my parser in my copy of your `main.py`, which creates new config options, I call my prompt generator just before [main.py#L202](https://github.com/mmabrouk/chatgpt-wrapper/blob/5474172138bc2582fe053ab1097b615869aea325/chatgpt_wrapper/main.py#L202), then pass it my prompts with `result = shell.run_command(shell.DEFAULT_COMMAND, prompt)`, at which point I can either just save the results and exit, or I can modify it to enter into the usual human shell interface to do manual steps once the initial setup is finished.

I realize that isn't a perfect fit for the existing planned design paradigm for `chatgpt-wrapper` or `chatgpt`, but it fits my use case and my existing code base pretty well with minimal changes.

**Comment by thehunmonkgroup** [comment]
I appreciate your efforts, and I also don't think this is a good fit for inclusion in the project.

The `response` object at that place in the code is pretty weird, and I'd sooner refactor how it's handled than create a situation where anyone depends on the return value.

If you're already hacking `main.py`, why don't you just monkey patch the existing `run` method on the `shell` instance? Then you can do whatever you want.

**Comment by ahundt** [comment]
Thanks! sure, np, just figured I'd check!

**Pull request closed without merging**
