### PR TITLE
Fix async update

### PR DESCRIPTION
**Pull request by Just1z**
Fixed async update. Works on Python 3.11

### CODE REVIEW

**Comment by thehunmonkgroup** [comment]
This looks close to a fix, but I' m running in to one issue: my test script is hanging at the end and not returning me to a command prompt. This is not happening w/ the async version of the class.

Here's my test script:

```python
#!/usr/bin/env python

from chatgpt_wrapper import ChatGPT

def main():
    bot = ChatGPT(False)
    response = bot.ask("Hello world!")
    print(response)

if __name__ == "__main__":
    main()
```

And the output, notice no prompt after the output, like the script is still running even though there is no more code to execute:

```
$ ~/test.py 
Hello there! How can I assist you today?

```

**Comment by Just1z** [comment]
I tried, but I can't reproduce this bug, it works fine for me on both 3.10 & 3.11

**Comment by thehunmonkgroup** [comment]
Let's hope it's just an issue with my local setup. Clearly the rest of this is needed, thanks for your work!

**Comment by SuperKenVery** [comment]
I tried, but I reproduce the bug, hanging when it should exits. 

```shell
(chatgpt-wrapper) ➜  ~ uname -a
uname -a
Darwin ken.local 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:39:35 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T8103 arm64
(chatgpt-wrapper) ➜  ~ python
Python 3.11.0 | packaged by conda-forge | (main, Jan 14 2023, 12:26:40) [Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

**Pull request merged**
