### PR TITLE
Changed hardcoded path to use OS-specific path for improved system support

### PR DESCRIPTION
**Pull request by Natanel-Shitrit**
The current main branch creates `tmp` folder in my root directory on my Windows machine.

### CODE REVIEW

**Review by mmabrouk — APPROVED** [review]
thanks!

**Comment by mmabrouk** [comment]
I needed to revert the PR. Using different tmp folder each time, makes it so that you need to login each time again when calling the command.

we need to use the same tmp folder. Can you please modify it to do so

**Comment by Natanel-Shitrit** [comment]
This change will not result in a new temp folder every time, it will always use the same folder. (for windows, as long as you are logged to the same user)
image

**Comment by Natanel-Shitrit** [comment]
@mmabrouk Would you like me to PR again?

**Comment by mmabrouk** [comment]
Sorry for the late answer. The issue is that tempfile.gettempdir() does return a different tmp folder in macos, since it seems to have two types of tmp folders, one in /tmp, and some dynamically generated ones in /var/folders/randomnumber.

**Comment by mmabrouk** [comment]
one solution wouldbe to check for the os in the code and then assign the tmp folders accordingly

import sys

# Check the platform
if sys.platform == 'darwin':
    print('This machine is running macOS')

**Pull request merged**
