### PR TITLE
Fixed extra blank page.

### PR DESCRIPTION
**Pull request by yerodin**

### CODE REVIEW

**Comment by mmabrouk** [comment]
Thanks for the PR, that is appreciated!
Could you please provide more information about the problem and your solution?

**Comment by yerodin** [comment]
Sure!

I am not sure if this happens on all platforms, but on initialization, the browser spawns the openai login page in addition to an extra blank page. 

The changes I made just checks if there is already an existing page  to use since browser.new_page() seems to create an additional page leaving the existing page blank if any.

I am using Debian Bookworm.

**Comment by Tecuya** [comment]
Oh cool, I actually spent a few minutes trying to get rid of that blank window before.  Your fix looks fine to me.

**Comment by mmabrouk** [comment]
Thanks a lot for the contribution and for the explanation!

**Comment by yerodin** [comment]
No problem! I am planning to use the project so I may look into more fixes/improvements. 

Cheers 🍻

**Pull request merged**
