### PR TITLE
Use single browser/page

### PR DESCRIPTION
**Pull request by SuperKenVery**
To reduce risk of Access denied

### CODE REVIEW

**Comment by thehunmonkgroup** [comment]
As I mentioned at https://github.com/mmabrouk/chatgpt-wrapper/pull/122#discussion_r1117932445, I'm not convinced this is the correct implementation.

Here are some use cases of the `ChatGPT` class I can think of:

1. User runs one session from CLI: probably the most common. This change would not be necessary.
2. User runs multiple sessions from CLI: one browser would be created for each CLI session, because they are running in a different process. This change would not help.
3. User invokes `ChatGPT` class themselves multiple times in one process, and want to use the the same browser instance for each. This change could be helpful.
4. User invokes `ChatGPT` class themselves in one process, and wants to use different browser instances for each invocation. **This change would break that ability**
5. User invokes `ChatGPT` class themselves in multiple processes. This change would not help.

In the above, only case 3 could be helped by this change, and it would simultaneously make case 4 not possible.

Now the current implementation of creating a browser instance does seem to be limited to one currently, but I think this is a function of our implementation, and not a limitation of Playwright, see https://github.com/microsoft/playwright/issues/1736#issuecomment-612427682

I would propose a different change: make the creation of the browser instance its own class, which returns a fully instantiated browser object, and this can be passed to the `ChatGPT` class. During `__init__`, the `ChatGPT` class could simply invoke the browser creation class itself if no browser object was passed in.

This would require only minor changes to the shell and API wrappers, should account for all use cases above, and by default would provide the same functionality as now.

It's possible there might be even better implementations than the one above, but any implementation should expand the options developers have, without removing any. It's also possible I'm misunderstanding or missing something, if so, please elaborate :)

**Comment by SuperKenVery** [comment]
> make the creation of the browser instance its own class, which returns a fully instantiated browser object, and this can be passed to the ChatGPT class.

This seems good. 

However, I don't get **why** one would want **multiple browser instances**. It eats your resources, and I don't see any benefits. With a single instance and page we can still have multiple conversations, because `conversation id`s are unique to every `ChatGPT` instance.

**Comment by thehunmonkgroup** [comment]
Easy answer: multiple users, one per browser. This may not be viable at the moment, but I could envision scenarios where it would.

There's no reason to box ourselves in when we can think clearly and engineer this well in the first place ;)

**Comment by SuperKenVery** [comment]
Make sense. Will do that.

**Comment by SuperKenVery** [comment]
Done!

**Comment by SuperKenVery** [comment]
Ahh, I found a big problem.

According to results from running this tiny test file,
[playwright-gc-test.py.txt](https://github.com/mmabrouk/chatgpt-wrapper/files/10839960/playwright-gc-test.py.txt)

A playwright's browser won't close the browser when the BrowserContext objects has been GarbageCollect'ed. That's annoying. We need to **manually** close the page and browser when the `ChatGPT` object is released, and what's worse:
- We might be sharing a browser instance with other `ChatGPT` objects, it was **passed in** during `__init__`
- We might be sharing a browser instance with other `ChatGPT` objects due to code like `b=ChatGPT(browser=a.browser)`
- We might be simply using the browser we created and no one else is using it. 

We have to do manual memory management now :(

A few options I can come up with:
- Making the browser attribute private, so it will not be used by external code, and we can safely close browser instances we created and preserve ones shared. I kinda like this. 
- Modify `playwright`'s code, which seems to be quite difficult. 
- Write another reference counter / GC :(

It's really disappointing that we have to consider this sort of thing in python :sob: 

What do you think?

**Comment by SuperKenVery** [comment]
Ah.... I just used a second browser instance to access ChatGPT and my account got instantly restricted...

Now I always receive 429 too many requests....

**Comment by thehunmonkgroup** [comment]
That is disappointing. I would think the best solution would be getting them to fix it in Playwright, but also the hardest. Certainly worth filing a ticket for, though...

Correct me if I'm wrong, but the use case we were enabling was allowing multiple `ChatGPT` classes to use browsers in the same process. In this case, it might be the caller's responsibility to manage finally closing the browser, since it is the thing that knows at a higher level if there is any other object still using it. Not ideal, but reasonable.

Did you get that 429 error on the Plus subscription, or the free one? I'd be surprised if Plus had that issue.

**Comment by SuperKenVery** [comment]
> but the use case we were enabling was allowing multiple ChatGPT classes to use browsers in the same process.

I'm considering something like this:
```python
a=ChatGPT(browser='firefox') # Create new browser
b=ChatGPT(browser=a.browser) # Use existing
# When a gets released it shouldn't release the browser :(
```

So I kinda think making the `browser` attribute private will make things easier. 

> Did you get that 429 error on the Plus subscription, or the free one? I'd be surprised if Plus had that issue.

The free one haha

**Comment by SuperKenVery** [comment]
I found an elegant way to do it... Wrap the BrowserContext around another class, and define the new class's `__del__`. 
I named the new class `Browser`, and I also moved session management into `Browser`. 

😄

**Comment by SuperKenVery** [comment]
We moved to async! 🎉 

The async change introduced a lot of conflicts, but I don't want to merge them right now, because I think there's still [something](https://github.com/mmabrouk/chatgpt-wrapper/pull/169/files#r1119639161) that can be done with the async code. 🤔 

I don't want to use `asyncio.run` in `__init__` but to keep coding style I have to. I think we can have a discussion on the async chage before I decide how to merge this code (and how to make the `Browser` object async). 😃

**Comment by SuperKenVery** [comment]
[issue of playwright-python](https://github.com/microsoft/playwright-python/issues/1787)

Okay, they think this is expected. 

Well, okay anyway, I found an elegant solution.

**Comment by thehunmonkgroup** [comment]
Looks like there are conflicts from my last round of changes. Definitely want to make sure the new browser class is up to date.

**Comment by SuperKenVery** [comment]
Hmmm, I decided to rewrite this based on the latest `main` branch, so I made a new PR. Closing this one~

**Pull request closed without merging**
