### PR TITLE
Feat: function to switch chat by uuid in the address bar

### PR DESCRIPTION
**Pull request by carlos-wong**
Hi, I just added a function which could choose the chat by uuid and get parent message id by query the chat info. 

it could make the user keep at  same chat when try to write a novel or something else.

### CODE REVIEW

**Review by thehunmonkgroup — CHANGES_REQUESTED** [review]
1. There have been some breaking changes, so the code will need to be updated
2. We'd need support for the shell as well, maybe a `!chat` command
3. Some of the recent changes allow providing a number argument to select a conversation from the history list, we'd want to support this, see https://github.com/mmabrouk/chatgpt-wrapper/commit/6c9fbcb8f6b4c7366be6380546281dc1da85b37c for an example implementation

**Comment by carlos-wong** [comment]
@thehunmonkgroup I just added chat command into the shell, and add json filter when the conversation_info include json invalid char(list: \n) to make the load.json work when chat is contain control char.

**Comment by thehunmonkgroup** [comment]
I appreciate the work so far, and there's a lot of refactoring that needs to be done. This feature should:

* Leverage the `_api_get_request()` method to fetch the conversation info, it's much cleaner than the XHR stuff, which we only really need to deal with streaming responses.
* In the shell, allow the user to also specify an ID from the `!history` command. Pull the latest changes and see how the new `!title` command is coded, that should give you a lot of guidance for implementing this feature.

**Comment by carlos-wong** [comment]
- I tried the _api_get_request, the conversation will timeout.  Also the set_title function. So I think there is difference of use the api and direct call in html.
- I suggest use uuid for now, user can get the uuid from browser. after implement the list chat function, we can make the user choose chat direct from list. at that time we can remove !chat command.

**Comment by carlos-wong** [comment]
@thehunmonkgroup and there is keep happen invalid control char of conversation response. Maybe because of I use Chinese char. So for now I switch to use regex to get the current_node info.

**Comment by thehunmonkgroup** [comment]
I really do not want commit any more code that uses the XHR hack unless it is absolutely necessary, and I'm not buying yet that it is ;)

`set_title()` has worked flawlessly for me, can you provide the exact code you're using to try that approach? What *exactly* is happening in the timeout? Are you sure that timeout issue is not just a transient result of OpenAI's servers being temporarily overloaded?

**Comment by carlos-wong** [comment]
I just test set_title , it is work now. I am recorded the old log: playwright._impl._api_types.Error: Connection timeout .
It is also happened when I am use the get api to get conversation. I checked the network when the timeout happen, the website official version is work fine. 

It is fine. I will keep my version.

**Comment by thehunmonkgroup** [comment]
I would be surprised if there was a difference on their end between handling and XHR request to their API endpoint, and the same basic request via some other method, especially when the error you're getting is a timeout. If you got a 403 or somesuch, then maybe that would suggest some validation they are doing.

I'm sure one of the reasons I don't have these issues with timeouts, etc., is that I'm on the ChatGPT Plus subscription.

**Comment by carlos-wong** [comment]
I using ChagtGPT plus too. I think the issue is we miss some info to pass by get api method. But in real, I don't think it is worth pay time on this problem. Because I think after OpenAI release the official API, we will need this hack way.

**Comment by thehunmonkgroup** [comment]
`!switch` and `!chat` commands have been added recently, perhaps they will be of help to you

**Comment by carlos-wong** [comment]
yes, I checked the code. thanks.

**Pull request closed without merging**
