### PR TITLE
use js to hit chatgpt api.  output in markdown.  input in readline.

### PR DESCRIPTION
**Pull request by Tecuya**
In my fork, I have altered the way your wrapper works quite a bit.  Here are a list of changes you will find here:

* It now works by evaluating our own JS in to the browser to interact with the ChatGPT API directly, rather than interacting with the website textarea/button and conversation dom elements.  This is more responsive and produces higher quality output.  We now get pure markdown output from ChatGPT.
* Improve output: Use `rich` library to render ChatGPT's markdown output in a fancy and terminal friendly way.. adds word wrapping to fit your terminal.  
* Improve input: Use `readline` library to improve interactive mode editing..  you can use the arrow keys now. it even has history.
* Conversation clear feature.  Uses `cmd` library to implement custom commands in the interpreter. now you can say "clear" to clear your conversational context. "exit" is also supported
* Switched the browser to Firefox.  In my experience, Firefox can log in to Google oauth and Chromium can not (when its being remote-controlled)

The contributions on this fork are licensed under the MIT license to match the parent project.

### CODE REVIEW

**Review by dylanbud — APPROVED** [review]

**Comment by Tecuya** [comment]
Demo
```sean@creosote:~/git/chatgpt-wrapper$ python3 chatgpt_wrapper/chatgpt.py 
Welcome to chatgpt-wrapper.  Provide a prompt for ChatGPT, or type help or ? to list commands.
> help

Documented commands (type help <topic>):
========================================
clear  exit  help

> help clear
`clear` starts a new conversation, chatgpt will lose the conversations context.
> what are fish

Fish are aquatic animals that belong to the class of vertebrates called Pisces. They are cold-blooded, have     
gills for breathing, and are typically covered in scales. Fish live in water and can be found in lakes, rivers, 
streams, and oceans all over the world. There are over 32,000 known species of fish, which come in a wide       
variety of shapes, sizes, and colors. Some common examples of fish include salmon, tuna, goldfish, and          
clownfish.                                                                                                      

> clear
* Conversation cleared.
> continue what you were saying

I'm sorry, but I am not able to continue a conversation as I am a large language model trained by OpenAI and do 
not have the ability to retain information or continue conversations. I can answer questions you have or provide
information on a wide range of topics, but I do not have the ability to remember previous conversations or      
continue them. Is there something specific you would like to ask or discuss?                                    

> exit
sean@creosote:~/git/chatgpt-wrapper$ 
```

**Comment by peteygao** [comment]
This might be a dumb question, but if you're already interacting with their API rather than the chat UI, why not bypass the complexity and slowness of Playwrite/browser and just write a CLI script that _directly_ interacts with their API by passing in the `Authorization: Bearer <Token>` which the user has to fish out of their browser (1 time thing)?

**Comment by Tecuya** [comment]
@peteygao Nah that's a good point.  I think what the user would need to fish out of the browser would be some kind of session cookie, with which we could then make an API call to the "session" endpoint to fetch a new bearer token.  The bearer tokens expire relatively quickly, I'm pretty sure.  But the session cookies should last longer.  It would really be nice to not need playwright.

**Review by mmabrouk — APPROVED** [review]

**Comment by mmabrouk** [comment]
Thanks for submitting your pull request! I appreciate your suggestion to interact with the API directly and I agree that it's the right way to go.

I also agree that the current limitations of the code, such as the use of sync mode in playwright and the inability to handle multiple conversations at once, can be addressed by implementing Peteygao's idea.

Let's work together to address these issues and improve the code.

Thanks again for your contribution!

**Pull request merged**
